# Generated by Django 5.1.4 on 2024-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0004_alter_post_options_post_author_post_tags_post_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
